import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Details from '../components/Details';
import Skills from '../components/Skills';
import Experience from '../components/Experience';
import Projects from '../components/Projects';
import MyStack from '../components/MyStack';
import Divider from '@mui/material/Divider';
import Contact from '../components/Contact';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Deshmukh P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Details />
      <Skills />
      <MyStack />
      <Experience />
      <Projects />
      <div className={styles.footer}>
        <Contact />
      </div>
    </div>
  )
}

export default Home
